### ISSUE TITLE
Installing stimela on Mac

### ISSUE THREAD

**Issue by Sinenhlanhla** [ratt-ru/Stimela#347]
I've been getting this error when installing stimela on Mac (macOS Mojave 10.14.2)

(stimela-env) 64-5a-ed-f3-8c-c:stimela-env Sinenhlanhla$ stimela build
Running: docker build --force-rm -f /var/folders/9y/59tdk0ld19j71wkhpl3b29q40000gn/T/tmpbgpmBJ/tmplmL4QY -t Sinenhlanhla_cab/tigger_tag /var/folders/9y/59tdk0ld19j71wkhpl3b29q40000gn/T/tmpbgpmBJ
invalid argument "Sinenhlanhla_cab/tigger_tag" for "-t, --tag" flag: invalid reference format: repository name must be lowercase

See 'docker build --help'.

Traceback (most recent call last):
  File "/Users/Sinenhlanhla/venv_stimela/stimela-env/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/Users/Sinenhlanhla/venv_stimela/stimela-env/lib/python2.7/site-packages/stimela/__init__.py", line 631, in main
    _cmd(argv)
  File "/Users/Sinenhlanhla/venv_stimela/stimela-env/lib/python2.7/site-packages/stimela/__init__.py", line 172, in build
    build_args=build_args, args=no_cache)
  File "/Users/Sinenhlanhla/venv_stimela/stimela-env/lib/python2.7/site-packages/stimela/docker.py", line 41, in build
    bdir])
  File "/Users/Sinenhlanhla/venv_stimela/stimela-env/lib/python2.7/site-packages/stimela/utils/__init__.py", line 151, in xrun
    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command, process.returncode))
stimela.utils.StimelaCabRuntimeError: docker build: returns errr code 125

**Comment by SpheMakh** [comment]
not sure if is this is still a problem. re-open if so
