### ISSUE TITLE
WSClean fails creating MMAP

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#437]
Looks like version 2.6 doesn't work
```
WARNING: This measurement set has no or an invalid WEIGHT_SPECTRUM column; will use less informative WEIGHT column.
Reordering /home/jenkins/msdir/kat-7-small-corr.ms into 1 x 1 parts.
Reordering: 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Initializing model visibilities: 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Detected 240.2 GB of system memory, usage not limited.
Opening reordered part 0 spw 0 for /home/jenkins/msdir/kat-7-small-corr.ms
Writing changed model back to /home/jenkins/msdir/kat-7-small-corr.ms:
 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Cleaning up temporary files...
+ + + + + + + + + + + + + + + + + + +
+ An exception occured:
+ >>> Error creating memory map to temporary model file: mmap() returned MAP_FAILED with error message: Invalid argument
+ + + + + + + + + + + + + + + + + + +

Traceback (most recent call last):
  File "/scratch/code/run.py", line 121, in <module>
    utils.xrun(cab['binary'], args + [mslist])
  File "/scratch/stimela/utils/__init__.py", line 111, in xrun
    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command, process.returncode))
utils.StimelaCabRuntimeError: wsclean: returns errr code 255
```

**Comment by bennahugo** [comment]
I will upgrade and see if Andre has fixed it otherwise there is more troubles...

**Comment by bennahugo** [comment]
@SpheMakh 2.7 don't fix this either. I'm going to send andre an email.
