### ISSUE TITLE
Tricolour udocker and singularity cabs broken

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#461]
As raised by Viral
```
2019-09-12 05:55:44,126 - STIMELA - INFO - Saving pipeline information in .last_meerkat:_basic_calibration.json
INFO:STIMELA:Saving pipeline information in .last_meerkat:_basic_calibration.json
Traceback (most recent call last):
  File "/home/parekh/stimela/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/parekh/stimela/local/lib/python2.7/site-packages/stimela/main.py", line 639, in main
    _cmd(argv)
  File "/home/parekh/stimela/local/lib/python2.7/site-packages/stimela/main.py", line 261, in run
    exec(stdr.read(), _globals)
  File "<string>", line 434, in <module>
  File "/home/parekh/stimela/local/lib/python2.7/site-packages/stimela/recipe.py", line 1054, in run
    raise_(pe, None, sys.exc_info()[2])
  File "/home/parekh/stimela/local/lib/python2.7/site-packages/stimela/recipe.py", line 1025, in run
    run_job()
  File "/home/parekh/stimela/local/lib/python2.7/site-packages/stimela/recipe.py", line 147, in run_udocker_job
    self.job.create()
  File "/home/parekh/stimela/local/lib/python2.7/site-packages/stimela/udocker.py", line 136, in create
    "udocker", ["create", "--name={0:s}".format(self.name), self.image])
  File "/home/parekh/stimela/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 124, in xrun
    '%s: returns errr code %d' % (command, process.returncode))
stimela.recipe.PipelineException: Exception occurred while running pipeline component 'flagpass1': udocker: returns errr code 1
```

Note: docker cabs works

**Comment by SpheMakh** [comment]
Fixed
