### ISSUE TITLE
Stimela build error: repository name must be lowercase

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/Stimela#487]
Opening this on behalf of @rozeenaebrahim, who is getting an error while installing stimela:

```
(meerkathi-venv-python3) [Rozeena@wcap Stimela]$ stimela build
Running: docker build --force-rm -f /tmp/tmpzdphs008/tmp7d4wj7k9 -t Rozeena_cab/eidos /tmp/tmpzdphs008
invalid argument "Rozeena_cab/eidos" for t: Error parsing reference: "Rozeena_cab/eidos" is not a valid repository/tag: repository name must be lowercase
See 'docker build --help'.
Traceback (most recent call last):
  File "/HddData/home/Rozeena/meerkathi-venv-python3/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/HddData/home/Rozeena/Stimela/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/HddData/home/Rozeena/Stimela/stimela/main.py", line 640, in main
    _cmd(argv)
  File "/HddData/home/Rozeena/Stimela/stimela/main.py", line 132, in build
    build_args=build_args, args=no_cache)
  File "/HddData/home/Rozeena/Stimela/stimela/docker.py", line 42, in build
    bdir])
  File "/HddData/home/Rozeena/Stimela/stimela/utils/__init__.py", line 166, in xrun
    '%s: returns errr code %d' % (command, process.returncode))
stimela.utils.StimelaCabRuntimeError: docker build: returns errr code 125

```

Just to confirm, this happens due to the username being in caps? Is there a way to fix this?

**Comment by SpheMakh** [comment]
Interesting, it seems docker does noot like upper case characters. I'll work on a fix, in the meantime, you can use the `build-label` option when building and running

To build
```
stimela build -bl rozeena_cab
```

Then to run
```
stimela run <pipeline> -bl rozeena_cab
```

**Comment by SpheMakh** [comment]
I suppose Docker did not anticipate users breaking this guideline

```
adduser: Please enter a username matching the regular expression configured
via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname'

```
