### ISSUE TITLE
Installation crashes when installing on ilifu with singularity

### ISSUE THREAD

**Issue by gigjozsa** [ratt-ru/Stimela#501]
```
(meerkathi) jozsa@slwrk-127:/scratch/users/jozsa/software$ stimela pull --singularity --pull-folder /scratch/users/jozsa/software
Traceback (most recent call last):
  File "/scratch/users/jozsa/software/virtualenv/meerkathi/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/scratch/users/jozsa/software/virtualenv/meerkathi/lib/python3.7/site-packages/stimela/main.py", line 640, in main
    _cmd(argv)
  File "/scratch/users/jozsa/software/virtualenv/meerkathi/lib/python3.7/site-packages/stimela/main.py", line 316, in pull
    log = logger.StimelaLogger(LOG_FILE, jtype=jtype)
  File "/scratch/users/jozsa/software/virtualenv/meerkathi/lib/python3.7/site-packages/stimela/utils/logger.py", line 26, in __init__
    if self.info.get(item, None) is None:
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by bennahugo** [comment]
Hi I cannot reproduce this under python 3 on stills.ru.ac.za with the current master (#6b1d79f6d0ae9722eda213e1f63b832499f13c90). Is this perhaps a permissions error with the NFS file system you are using? Try running it in your home instead.

**Comment by bennahugo** [comment]
Actually the only way I can see this happening is if pyyaml returns None for some reason. Can you please ensure that your stimela_parameter files are cleaned before running this.

**Comment by gigjozsa** [comment]
The whole thing is running now. In fact, I cleared out .stimela before installing.
I also tried to care that the home folder is not too full by using symlinks (but that has probably nothing to do with this issue):
```
mkdir /scratch/users/jozsa/software
mv /users/jozsa/.cache /scratch/users/jozsa/software/
ln -s /scratch/users/jozsa/software/.cache /users/jozsa/.cache
rm -rf /users/jozsa/.stimela
mkdir /scratch/users/jozsa/software/.stimela
ln -s /scratch/users/jozsa/software/.stimela /users/jozsa/.stimela
mkdir /scratch/users/jozsa/software/.singularity
ln -s /scratch/users/jozsa/software/.stimela /users/jozsa/.singularity
rm ~/.stimela
```
or similar

After that
```
stimela pull --singularity --pull-folder /scratch/users/jozsa/software/
```
is working.
