### ISSUE TITLE
Cannot build Stimela

### ISSUE THREAD

**Issue by paoloserra** [ratt-ru/Stimela#523]
I was way behind with Stimela and tried to update with

```
$ rm ~/.stimela/*
$ pip install --upgrade git+https://github.com/SpheMakh/Stimela
$ stimela build
```

(All of the above was done inside the meerkathi venv.)

I get the following error:

```
Running: docker build --force-rm -f /tmp/tmpa6w0ni0p/tmp1k0giu_a -t pserra_cab/cubical /tmp/tmpa6w0ni0p
Sending build context to Docker daemon  96.26kB
Step 1/8 : FROM stimela/cubical:1.3.0
unexpected EOF
Traceback (most recent call last):
  File "/home/pserra/Astro/menv3/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/pserra/Astro/menv3/lib/python3.5/site-packages/stimela/main.py", line 640, in main
    _cmd(argv)
  File "/home/pserra/Astro/menv3/lib/python3.5/site-packages/stimela/main.py", line 132, in build
    build_args=build_args, args=no_cache)
  File "/home/pserra/Astro/menv3/lib/python3.5/site-packages/stimela/docker.py", line 42, in build
    bdir])
  File "/home/pserra/Astro/menv3/lib/python3.5/site-packages/stimela/utils/__init__.py", line 181, in xrun
    '%s: returns errr code %d' % (command, process.returncode))
stimela.utils.StimelaCabRuntimeError: docker build: returns errr code 1
```

Any suggestion?

**Comment by KshitijT** [comment]
If docker:

```
rm ~/.stimela/*
pip install --upgrade git+https://github.com/SpheMakh/Stimela
stimela pull -d
stimela build
```
should be the process?

**Comment by paoloserra** [comment]
Thanks, will try and let you know

**Comment by paoloserra** [comment]
that worked, thanks again @KshitijT
