### ISSUE TITLE
stimela pull -d fails

### ISSUE THREAD

**Issue by gigjozsa** [ratt-ru/Stimela#524]
```
> stimela pull -d
Running: docker pull stimela/casa:0.3.0
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:59191->[::1]:53: read: connection refused
Traceback (most recent call last):
  File "/home/jozsa/.virtualenv/meerkathi/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/jozsa/.virtualenv/meerkathi/lib/python3.5/site-packages/stimela/main.py", line 640, in main
    _cmd(argv)
  File "/home/jozsa/.virtualenv/meerkathi/lib/python3.5/site-packages/stimela/main.py", line 359, in pull
    docker.pull(image, force=args.force)
  File "/home/jozsa/.virtualenv/meerkathi/lib/python3.5/site-packages/stimela/docker.py", line 57, in pull
    utils.xrun("docker", ["pull", image])
  File "/home/jozsa/.virtualenv/meerkathi/lib/python3.5/site-packages/stimela/utils/__init__.py", line 181, in xrun
    '%s: returns errr code %d' % (command, process.returncode))
stimela.utils.StimelaCabRuntimeError: docker: returns errr code 1
```

but this is the [installation instruction for the Docker version](https://github.com/ratt-ru/Stimela/wiki/Installation#for-docker-support-step-2-pull-base-images).

**Comment by o-smirnov** [comment]
The first couple of lines suggest a network error rather than anything in Stimela. What happens if you just call ``docker pull stimela/casa:0.3.0`` by hand?

**Comment by gigjozsa** [comment]
Indeed,
```
0.3.0: Pulling from stimela/casa
Digest: sha256:dd9feaa73acae5d2266d0526a9a51105a3472c5e0fca156f4a54e397179538e6
Status: Image is up to date for stimela/casa:0.3.0
docker.io/stimela/casa:0.3.0
```
and a second attempt on ``stimela pull -d`` worked.
