### ISSUE TITLE
stimela runs through an error without crashing

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#554]
```
2020-04-13 10:03:58 STIMELA.image_target_0 INFO: running singularity run  --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/stimela/stimela:/scratch/stimela:ro --bind /data3/bhugo/CLUSTER
_SURVEY_TAKE2/stimela_parameter_files/image_target_0-1405556434287201586765032971066.json:/scratch/configfile:ro --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/stimela/stimela/cargo/ca
b/ddfacet/src:/scratch/code:ro --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/venvstimela/bin/stimela_singularity_run:/singularity:rw --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/msdir:/sc
ratch/msdir:rw --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/input:/scratch/input:ro --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/output:/scratch/output:rw --bind /data3/bhugo/CLUSTER_SUR
VEY_TAKE2/output/tmp:/scratch/output/tmp:rw /home/bhugo/.stimela_images/stimela_ddfacet_1.3.2.img /singularity
## Traceback (most recent call last):
##   File "/usr/local/bin/DDF.py", line 26, in <module>
##     from DDFacet.compatibility import range
##   File "/usr/local/lib/python3.6/dist-packages/DDFacet/__init__.py", line 23, in <module>
##     __version__ = pkg_resources.require("DDFacet")[0].version
##   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 901, in require
##     needed = self.resolve(parse_requirements(requirements))
##   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 792, in resolve
##     raise VersionConflict(dist, req).with_context(dependent_req)
## pkg_resources.ContextualVersionConflict: (scipy 1.4.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('scipy<=1.3.3'), {'DDFacet'})
2020-04-13 10:04:00 STIMELA.image_target_0 INFO: job complete at 2020-04-13 10:04:00.331345 after 0:00:01.607419
2020-04-13 10:04:00 STIMELA.mask_target_0 INFO: job started at 2020-04-13 10:04:00.331619
2020-04-13 10:04:00 STIMELA.MeerKAT: INTROSPECT selfcal pipeline INFO: STEP 2 :: mask calcycle_0 RXCJ1638.2-6420
2020-04-13 10:04:00 STIMELA INFO: Validating parameters...       CAB = cleanmask
2020-04-13 10:04:00 STIMELA INFO: Location of 'image' was specified as 'output'. Will overide default.
2020-04-13 10:04:00 STIMELA INFO: Parameters validated and saved. Parameter file is: stimela_parameter_files/mask_target_0-14055564344132815867650331129906.json
2020-04-13 10:04:00 STIMELA.mask_target_0 INFO: Starting container [063]. Timeout set to -1. The container ID is printed below.
2020-04-13 10:04:00 STIMELA.mask_target_0 INFO: running singularity run  --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/stimela/stimela:/scratch/stimela:ro --bind /data3/bhugo/CLUSTER_
SURVEY_TAKE2/stimela_parameter_files/mask_target_0-14055564344132815867650331129906.json:/scratch/configfile:ro --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/stimela/stimela/cargo/cab
/cleanmask/src:/scratch/code:ro --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/venvstimela/bin/stimela_singularity_run:/singularity:rw --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/msdir:/s
cratch/msdir:rw --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/input:/scratch/input:ro --bind /data3/bhugo/CLUSTER_SURVEY_TAKE2/output:/scratch/output:rw --bind /data3/bhugo/CLUSTER_SU
RVEY_TAKE2/output/tmp:/scratch/output/tmp:rw /home/bhugo/.stimela_images/stimela_astropy_1.2.0.img /singularity
```

**Comment by o-smirnov** [comment]
I think this is already fixed, just not PRed yet. The runscripts are [currently wrong](https://github.com/ratt-ru/Stimela/blob/master/stimela/cargo/cab/stimela_docker_run), there's no call to look at ``PIPESTATUS`` since there's no pipe.

Just have ``xvfb-run`` as the last line in the script so that its error code is passed outwards.

**Comment by bennahugo** [comment]
Need to be very careful here and perhaps add a test where a failure mode is induced. We had the tests but @SpheMakh took them out. I will try to put something back in.

**Comment by o-smirnov** [comment]
Induce? I experience failure modes on an hourly basis whether I want them or not. :)
