### ISSUE TITLE
Stimela will not install with docker on com06

### ISSUE THREAD

**Issue by gigjozsa** [ratt-ru/Stimela#583]
The diagnostics I have:
```
stimela build
# running docker build --force-rm -f /tmp/tmp1xokn9pj/tmp4yk8mit8 -t jozsa_cab/casa_fixvis /tmp/tmp1xokn9pj
# Sending build context to Docker daemon   7.68kB
# 
# Step 1/7 : FROM stimela/casa:1.2.5
#  ---> 45ce0420b27a
# Step 2/7 : MAINTAINER <sphemakh@gmail.com>
#  ---> Using cache
#  ---> 42f94f3900f5
# Step 3/7 : ADD src /scratch/code
#  ---> Using cache
#  ---> 9a025e6c1ba9
# Step 4/7 : ENV LOGFILE ${OUTPUT}/logfile.txt
#  ---> Using cache
#  ---> 902007ed3635
# Step 5/7 : RUN useradd -r -u 1788 -U jozsa
#  ---> Running in 06bfc06bad90
# Removing intermediate container 06bfc06bad90
# OCI runtime create failed: /var/lib/docker/overlay2/c47b8d46a8dac3b1dba4698cc9f3f4aa5de70236d8f327de6303450a52732aa0/merged is not an absolute path or is a symlink: unknown
Traceback (most recent call last):
  File "/scratch2/jozsa/ic1459/datared/caracal_venv/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/scratch2/jozsa/ic1459/datared/caracal_venv/src/stimela/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/scratch2/jozsa/ic1459/datared/caracal_venv/src/stimela/stimela/main.py", line 649, in main
    _cmd(argv)
  File "/scratch2/jozsa/ic1459/datared/caracal_venv/src/stimela/stimela/main.py", line 137, in build
    build_args=build_args, args=no_cache)
  File "/scratch2/jozsa/ic1459/datared/caracal_venv/src/stimela/stimela/docker.py", line 42, in build
    bdir])
  File "/scratch2/jozsa/ic1459/datared/caracal_venv/src/stimela/stimela/utils/xrun_poll.py", line 187, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: docker build returns error code 1
```

**Comment by bennahugo** [comment]
it looks like a broken docker installation. please raise the issue on
ratt-ru/systems

**Comment by o-smirnov** [comment]
OK it works now. Indeed docker was misconfigued. Who knew you couldn't just make a symlink, d'oh!
