### ISSUE TITLE
issue with sh for casa47 1.4.2

### ISSUE THREAD

**Issue by smasoka** [ratt-ru/Stimela#630]
I think commands passed to `sh -c` need to be wrapped in quotes. 

```
[smasoka@login1 ~]$ singularity run /apps/chpc/astro/stimela_images/stimela_casa47_1.4.2.sif 
Singularity> /bin/sh -c casa --help

=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

CASA Version 4.7.2-REL (r39762)
  Compiled on: Wed 2017/03/08 12:48:09 UTC
casalogger: cannot connect to X server :99
Traceback (most recent call last):
  File "/casa-release-4.7.2-el7/lib/python2.7/casapy.py", line 1319, in <module>
    pl.clf( )
  File "/casa-release-4.7.2-el7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 443, in clf
    gcf().clf()
  File "/casa-release-4.7.2-el7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 369, in gcf
    return figure()
  File "/casa-release-4.7.2-el7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 343, in figure
    **kwargs)
  File "/casa-release-4.7.2-el7/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 80, in new_figure_manager
    window = Tk.Tk()
  File "/casa-release-4.7.2-el7/lib/python2.7/lib-tk/Tkinter.py", line 1745, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":99"
Singularity> 
Singularity> 
Singularity> 
Singularity> 
Singularity> /bin/sh -c "casa --help"

=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

CASA Version 4.7.2-REL (r39762)
  Compiled on: Wed 2017/03/08 12:48:09 UTC
Options are: 
   --rcdir directory
   --logfile logfilename
   --maclogger
   --log2term
   --nologger
   --nologfile
   --nogui
   --colors=[NoColor|Linux|LightBG]
   --pipeline
   -c filename-or-expression
   --help, print this text and exit

Singularity> 
```

**Comment by SpheMakh** [comment]
Is this still a problem?
