### ISSUE TITLE
Working on nash: 'podman' specified in stimela script but get "docker: not found"

### ISSUE THREAD

**Issue by svw26** [ratt-ru/Stimela#648]
Heylo,

I thought I'd get into gear again by running the master branch of MosaicSteward using Stimela. All fine. I then updated Stimela and re-ran my test, but this time got error messages. I have been working on nash, where podman was recommended, but is no longer fully supported. The contents of the stimela script are as follows:

```
import stimela
import os
## Define the necessary variables
MOSAIC_TYPE = 'continuum'
DOMONTAGE = True
CUTOFF = 0.25
NAME = "test_mosaic_cab_121219"
MSDIR = "msdir"
INPUT = "user_input"
OUTPUT = "user_output"
TARGET_IMAGES = ['continuum/slice_of_j0831-5517-ska_HI.image.fits', 'continuum/slice_of_j0836-5552-ska_HI.image.fits', 'continuum/slice_of_j0839-5517-ska_HI.image.fits']
stimela.register_globals()

## Form a 'recipe'
recipe = stimela.Recipe('Testing the MosaicSteward cab', ms_dir=MSDIR, JOB_TYPE='podman')

## Add an ingredient to the recipe: 
recipe.add('cab/mosaicsteward', 'mosaicsteward',{
     "mosaic-type" : MOSAIC_TYPE,
     "domontage": DOMONTAGE,
     "cutoff": CUTOFF,
     "name": NAME,
     "target-images": TARGET_IMAGES,
     },
     input=INPUT,
     output=OUTPUT,
     label='MosaicSteward:: Testing the MosaicSteward cab')

recipe.run()
```

Attached are the two log files that were output, and below is the end of the terminal output that I managed to grab.

Thanks,
Sarah x

\# /bin/sh: 1: docker: not found
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: docker create returns error code 127
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: job failed at 2020-06-17 11:34:46.172428 after 0:00:00.005429
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: Traceback (most recent call last):
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: File "/home/sarahwhite/meerkathi-venv3/lib/python3.6/site-packages/stimela/recipe.py", line 689, in run
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: job.run_job()
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: File "/home/sarahwhite/meerkathi-venv3/lib/python3.6/site-packages/stimela/recipe.py", line 421, in run_job
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: self.job.create(*self.args)
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: File "/home/sarahwhite/meerkathi-venv3/lib/python3.6/site-packages/stimela/docker.py", line 129, in create
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: self.RUNSCRIPT or ""], log=self.logger)
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: File "/home/sarahwhite/meerkathi-venv3/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 189, in xrun
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2020-06-17 11:34:46 STIMELA.mosaicsteward ERROR: stimela.utils.StimelaCabRuntimeError: docker create returns error code 127
2020-06-17 11:34:46 STIMELA.Testing the MosaicSteward cab INFO: Completed jobs : []
2020-06-17 11:34:46 STIMELA.Testing the MosaicSteward cab INFO: Remaining jobs : []
2020-06-17 11:34:46 STIMELA.Testing the MosaicSteward cab INFO: Saving pipeline information in .last_Testing_the_MosaicSteward_cab.json
Traceback (most recent call last):
  File "/home/sarahwhite/meerkathi-venv3/bin/stimela", line 14, in <module>
  main.main([a for a in sys.argv[1:]])
  File "/home/sarahwhite/meerkathi-venv3/lib/python3.6/site-packages/stimela/main.py", line 601, in main
  _cmd(argv)
  File "/home/sarahwhite/meerkathi-venv3/lib/python3.6/site-packages/stimela/main.py", line 215, in run
  exec(stdr.read(), _globals)
  File "<string>", line 29, in <module>
  File "/home/sarahwhite/meerkathi-venv3/lib/python3.6/site-packages/stimela/recipe.py", line 740, in run
  raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'MosaicSteward:: Testing the MosaicSteward cab' failed: docker create returns error code 127

[log-Testing_the_MosaicSteward_cab.txt](https://github.com/ratt-ru/Stimela/files/4791803/log-Testing_the_MosaicSteward_cab.txt)
[log-Testing_the_MosaicSteward_cab-mosaicsteward.txt](https://github.com/ratt-ru/Stimela/files/4791807/log-Testing_the_MosaicSteward_cab-mosaicsteward.txt)

**Comment by svw26** [comment]
And I updated Stimela by checking that I was on my local 'master' branch then doing:
```
git pull
pip install stimela -U
```
which completed with:

Successfully installed future-fstrings-1.2.0 stimela-1.6.2
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by KshitijT** [comment]
You probably need to do pip install -e . -U in the stimela folder. I don't think the pip version (which you are installing via `pip install stimela` has the fix yet.

**Comment by svw26** [comment]
Thanks, @KshitijT ! The installation completes with:

Successfully installed scabha-0.3.0 stimela
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

and the script completes successfully using "Stimela version 1.6.3" x
