### ISSUE TITLE
multiscale-scales does not work any more

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/Stimela#650]
Something seems to be wrong with the new master / release version of stimela. I used to set multiscale-scales as:

`      "multiscale-scales": [0,10,20,40,80,160,320,400],
`
However, running the same script after a stimela update gives an error:

```
# 2020-06-21 17:05:42: Running wsclean -name /stimela_mount/output/circinus-full-2-flagged-briggs_0.0_fullmask2_small -j 32 -mem 100 -no-update-model-required -weight briggs 0.0 -size 500 500 -scale 1.3arcsec -channels-out 32 -no-small-inversion -pol I -data-column CORRECTED_DATA -niter 3000000 -auto-threshold 0.001 -auto-mask 5 -gain 0.1 -mgain 0.9 -join-channels -multiscale -multiscale-scales 0 10 20 40 80 160 320 400 -fit-spectral-pol 2 -deconvolution-channels 4 -nmiter 20 /stimela_mount/msdir/1532022061_8s-circinus_p3_corr.ms
# 
# WSClean version 2.9.0 (2020-03-27)
# This software package is released under the GPL version 3.
# Author: André Offringa (offringa@gmail.com).
# 
# + + + + + + + + + + + + + + + + + + +
# + An exception occured:
# + >>> Table /stimela_mount/output/10 does not exist
# + + + + + + + + + + + + + + + + + + +
# 2020-06-21 17:05:43: wsclean exited with code 255
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: docker returns error code 1
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: job failed at 2020-06-21 17:05:43.446906 after 0:00:01.796875
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: Traceback (most recent call last):
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/recipe.py", line 693, in run
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     job.run_job()
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/recipe.py", line 423, in run_job
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     self.job.start(output_wrangler=self.apply_output_wranglers)
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/docker.py", line 171, in start
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     kill_callback=lambda: utils.xrun("docker", ["kill", self.name]))
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/utils/xrun_poll.py", line 189, in xrun
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: stimela.utils.StimelaCabRuntimeError: docker returns error code 1
2020-06-21 17:05:43 STIMELA.Image circinus broadband INFO: Completed jobs : []
2020-06-21 17:05:43 STIMELA.Image circinus broadband INFO: Remaining jobs : []
2020-06-21 17:05:43 STIMELA.Image circinus broadband INFO: Saving pipeline information in .last_Image_circinus_broadband.json
Traceback (most recent call last):
  File "/data2/kshitij/docker_shm_venv/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data2/kshitij/Stimela/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/data2/kshitij/Stimela/stimela/main.py", line 602, in main
    _cmd(argv)
  File "/data2/kshitij/Stimela/stimela/main.py", line 216, in run
    exec(stdr.read(), _globals)
  File "<string>", line 877, in <module>
  File "/data2/kshitij/Stimela/stimela/recipe.py", line 744, in run
    raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'image_3_briggs_0_fullmask2_small::Image' failed: docker returns error code 1
```

Runs fine if I don't specify multiscale-scales. 

If the format has changed, please update the documentation.

**Comment by viralp** [comment]
I am also getting a very similar error even without adding `"multiscale-scales"`

2020-06-24 14:31:08 STIMELA.image_combine_target INFO: ---------------------------------
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Stimela version 1.6.4
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Running: image_combine_target
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: ---------------------------------
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Config directory cannot be found. Will create /vault-ike/parekh/A3376/combine/.stimela_workdir-15930018686957643/stimela_parameter_files
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Adding cab 'stimela/wsclean:1.6.3' (2.9) to recipe, container name 'image_combine_target'
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: job started at 2020-06-24 14:31:08.764358
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: STEP 1 :: image_combine_target::Image the target field after selfcal
2020-06-24 14:31:08 STIMELA INFO: Validating parameters for cab wsclean (stimela/wsclean:1.6.3)
2020-06-24 14:31:08 STIMELA INFO: Location of 'prefix' was specified as 'output'. Will overide default.
2020-06-24 14:31:08 STIMELA INFO: Parameters validated and saved to /vault-ike/parekh/A3376/combine/.stimela_workdir-15930018686957643/stimela_parameter_files/image_combine_target-14033316727480015930018686971657.json
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Instantiating container [image_combine_target-14033316727480015930018686971657]. The container ID is printed below.
# running docker create --user 1123:1123 --shm-size 1gb  -v /vault-ike/parekh/A3376/combine/.stimela_workdir-15930018686957643/stimela_parameter_files/image_combine_target-14033316727480015930018686971657.json:/stimela_mount/configfile:ro -v /home/parekh/Stimela/stimela/cargo/cab/wsclean/src:/stimela_mount/code:ro -v /vault-ike/parekh/A3376/combine/.stimela_workdir-15930018686957643/passwd:/etc/passwd:rw -v /vault-ike/parekh/A3376/combine/.stimela_workdir-15930018686957643/group:/etc/group:rw -v /home/parekh/venvclean/bin/stimela_runscript:/docker_run:ro -v /vault-ike/parekh/A3376/combine/msdir:/stimela_mount/msdir:rw -v /vault-ike/parekh/A3376/combine/input:/stimela_mount/input:ro -v /vault-ike/parekh/A3376/combine/output_image_combine_target:/stimela_mount/output:rw -v /vault-ike/parekh/A3376/combine/output_image_combine_target/tmp:/stimela_mount/output/tmp:rw  -e CONFIG=/stimela_mount/configfile -e HOME=/stimela_mount/output -e STIMELA_MOUNT=/stimela_mount -e MSDIR=/stimela_mount/msdir -e INPUT=/stimela_mount/input -e OUTPUT=/stimela_mount/output -e TMPDIR=/stimela_mount/output/tmp --rm -w /stimela_mount/output --name image_combine_target-14033316727480015930018686971657 stimela/wsclean:1.6.3 /docker_run
# Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=image_combine_target-14033316727480015930018686971657: dial unix /var/run/docker.sock: connect: permission denied
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR: docker create returns error code 1
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR: job failed at 2020-06-24 14:31:08.820952 after 0:00:00.056594
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR: Traceback (most recent call last):
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:   File "/home/parekh/Stimela/stimela/recipe.py", line 693, in run
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:     job.run_job()
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:   File "/home/parekh/Stimela/stimela/recipe.py", line 421, in run_job
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:     self.job.create(*self.args)
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:   File "/home/parekh/Stimela/stimela/docker.py", line 129, in create
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:     self.RUNSCRIPT or ""], log=self.logger)
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:   File "/home/parekh/Stimela/stimela/utils/xrun_poll.py", line 189, in xrun
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2020-06-24 14:31:08 STIMELA.image_combine_target ERROR: stimela.utils.StimelaCabRuntimeError: docker create returns error code 1
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Completed jobs : []
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Remaining jobs : []
2020-06-24 14:31:08 STIMELA.image_combine_target INFO: Saving pipeline information in .last_image_combine_target.json
Traceback (most recent call last):
  File "/home/parekh/venvclean/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/parekh/Stimela/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/parekh/Stimela/stimela/main.py", line 602, in main
    _cmd(argv)
  File "/home/parekh/Stimela/stimela/main.py", line 216, in run
    exec(stdr.read(), _globals)
  File "<string>", line 48, in <module>
  File "/home/parekh/Stimela/stimela/recipe.py", line 744, in run
    raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'image_combine_target::Image the target field after selfcal' failed: docker create returns error code 1
