### ISSUE TITLE
provide cabs for RM synth tools

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/Stimela#670]
@francescaLoi can advise which, I believe she mentioned ``pyrmsynth`` and ``RM-tools``.

**Comment by francescaLoi** [comment]
Thanks @o-smirnov . @SpheMakh , `RM-tools` would be great!

**Comment by francescaLoi** [comment]
https://github.com/CIRADA-Tools/RM-Tools
We would need `rmsynth3d` and `rmclean3d` tools.

**Comment by SpheMakh** [comment]
Done. @francescaLoi can you try these cabs. see 

```
stimela cabs -i rmsynth3d
stimela cabs -i rmclean3d 
```

for usage

**Comment by SpheMakh** [comment]
You will need to install the `issue-670` branch of stimela and the `local-prefix` branch of scabha (https://github.com/ratt-ru/scabha)

**Comment by francescaLoi** [comment]
I tried with this very simple script (please check it):

```
import stimela

import os

INPUT = "input"  # This folder must exist
OUTPUT = "output"
MSDIR = "msdir"
PREFIX = "stimela-example"  # Prefix for output images
try:
    SINGULARTITY_IMAGE_DIR = os.environ["STIMELA_SINGULARTITY_IMAGE_DIR"]
except KeyError:
    SINGULARTITY_IMAGE_DIR = None


run = stimela.Recipe("run",     # Recipe name
                     ms_dir=MSDIR,
                          singularity_image_dir=SINGULARTITY_IMAGE_DIR,
                          log_dir=os.path.join(OUTPUT, "logs"),
                          )

run.JOB_TYPE = "docker"

run.add("cab/rmsynth3d",
            "rmsynth3d",
             {
                "fitsq": "4k_RMSYNTH-NGC1365_3-Q.fits",
                "fitsu": "4k_RMSYNTH-NGC1365_3-U.fits",
                "fitsi": "4k_RMSYNTH-NGC1365_3-I.fits",
                "freqs": "freqs.dat",
                "prefixout": "prova",
                "s": 10,
                "v": True,
             },
             input="output/continuum/rm_dir", output=OUTPUT,
             label="rmsynth obs")

run.run()
```
which didn't work. This is the output:
```
(stimela) floi@escondida2:/24TB/floi/POL_TEST$ stimela run stimela_rm.yml 
2020-11-30 13:15:22 STIMELA.run INFO: ---------------------------------
2020-11-30 13:15:22 STIMELA.run INFO: Stimela version 1.6.9
2020-11-30 13:15:22 STIMELA.run INFO: Running: run
2020-11-30 13:15:22 STIMELA.run INFO: ---------------------------------
2020-11-30 13:15:22 STIMELA.run INFO: Config directory cannot be found. Will create /24TB/floi/POL_TEST/.stimela_workdir-16067421224825203/stimela_parameter_files
2020-11-30 13:15:22 STIMELA.run INFO: Adding cab 'stimela/casa:1.6.9' (1.0.7) to recipe, container name 'rmsynth3d'
2020-11-30 13:15:22 STIMELA.rmsynth3d INFO: job started at 2020-11-30 13:15:22.498323
2020-11-30 13:15:22 STIMELA.run INFO: STEP 1 :: rmsynth obs
2020-11-30 13:15:22 STIMELA INFO: Validating parameters for cab rmsynth3d (stimela/casa:1.6.9)
2020-11-30 13:15:22 STIMELA INFO: Parameters validated and saved to /24TB/floi/POL_TEST/.stimela_workdir-16067421224825203/stimela_parameter_files/rmsynth3d-13987504642622416067421224837155.json
2020-11-30 13:15:22 STIMELA.rmsynth3d INFO: Instantiating container [rmsynth3d-13987504642622416067421224837155]. The container ID is printed below.
# running docker create --user 1000:1100 --shm-size 1gb  -v /24TB/floi/POL_TEST/.stimela_workdir-16067421224825203/stimela_parameter_files/rmsynth3d-13987504642622416067421224837155.json:/stimela_mount/configfile:ro -v /home/floi/.local/lib/python3.6/site-packages/stimela/cargo/cab/rmsynth3d/src:/stimela_mount/code:ro -v /24TB/floi/POL_TEST/.stimela_workdir-16067421224825203/passwd:/etc/passwd:rw -v /24TB/floi/POL_TEST/.stimela_workdir-16067421224825203/group:/etc/group:rw -v /home/floi/.local/bin/stimela_runscript:/docker_run:ro -v /24TB/floi/POL_TEST/msdir:/stimela_mount/msdir:rw -v /24TB/floi/POL_TEST/output/continuum/rm_dir:/stimela_mount/input:ro -v /24TB/floi/POL_TEST/output:/stimela_mount/output:rw -v /24TB/floi/POL_TEST/output/tmp:/stimela_mount/output/tmp:rw  -e CONFIG=/stimela_mount/configfile -e HOME=/stimela_mount/output -e STIMELA_MOUNT=/stimela_mount -e MSDIR=/stimela_mount/msdir -e INPUT=/stimela_mount/input -e OUTPUT=/stimela_mount/output -e TMPDIR=/stimela_mount/output/tmp --rm -w /stimela_mount/output --name rmsynth3d-13987504642622416067421224837155 stimela/casa:1.6.9 /docker_run
# Unable to find image 'stimela/casa:1.6.9' locally
# Error response from daemon: manifest for stimela/casa:1.6.9 not found: manifest unknown: manifest unknown
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR: docker create returns error code 1
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR: job failed at 2020-11-30 13:15:24.228995 after 0:00:01.730672
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR: Traceback (most recent call last):
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/recipe.py", line 703, in run
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:     job.run_job()
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/recipe.py", line 421, in run_job
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:     self.job.create(*self.args)
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/docker.py", line 127, in create
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:     self.RUNSCRIPT or ""], log=self.logger)
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2020-11-30 13:15:24 STIMELA.rmsynth3d ERROR: stimela.utils.StimelaCabRuntimeError: docker create returns error code 1
2020-11-30 13:15:24 STIMELA.run INFO: Completed jobs : []
2020-11-30 13:15:24 STIMELA.run INFO: Remaining jobs : []
2020-11-30 13:15:24 STIMELA.run INFO: Saving pipeline information in .last_run.json
Traceback (most recent call last):
  File "/home/floi/.local/bin/stimela", line 11, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/floi/.local/lib/python3.6/site-packages/stimela/main.py", line 567, in main
    _cmd(argv)
  File "/home/floi/.local/lib/python3.6/site-packages/stimela/main.py", line 195, in run
    exec(stdr.read(), _globals)
  File "<string>", line 36, in <module>
  File "/home/floi/.local/lib/python3.6/site-packages/stimela/recipe.py", line 754, in run
    raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'rmsynth obs' failed: docker create returns error code 1

```

**Comment by SpheMakh** [comment]
Fixed, can you pull and try again

**Comment by francescaLoi** [comment]
Almost there, it performs the rmsynthesis but cannot save the results. I also tried with `"prefixout": "prova:input"`, it complains anyway.
```
2020-11-30 15:02:58 STIMELA.run INFO: ---------------------------------
2020-11-30 15:02:58 STIMELA.run INFO: Stimela version 1.6.9
2020-11-30 15:02:58 STIMELA.run INFO: Running: run
2020-11-30 15:02:58 STIMELA.run INFO: ---------------------------------
2020-11-30 15:02:58 STIMELA.run INFO: Config directory cannot be found. Will create /24TB/floi/POL_TEST/.stimela_workdir-16067485787053518/stimela_parameter_files
2020-11-30 15:02:58 STIMELA.run INFO: Adding cab 'stimela/rm-tools:1.6.9-1' (1.0.7) to recipe, container name 'rmsynth3d'
2020-11-30 15:02:58 STIMELA.rmsynth3d INFO: job started at 2020-11-30 15:02:58.720680
2020-11-30 15:02:58 STIMELA.run INFO: STEP 1 :: rmsynth obs
2020-11-30 15:02:58 STIMELA INFO: Validating parameters for cab rmsynth3d (stimela/rm-tools:1.6.9-1)
2020-11-30 15:02:58 STIMELA INFO: Parameters validated and saved to /24TB/floi/POL_TEST/.stimela_workdir-16067485787053518/stimela_parameter_files/rmsynth3d-1399823203836001606748578706498.json
2020-11-30 15:02:58 STIMELA.rmsynth3d INFO: Instantiating container [rmsynth3d-1399823203836001606748578706498]. The container ID is printed below.
# running docker create --user 1000:1100 --shm-size 1gb  -v /24TB/floi/POL_TEST/.stimela_workdir-16067485787053518/stimela_parameter_files/rmsynth3d-1399823203836001606748578706498.json:/stimela_mount/configfile:ro -v /home/floi/.local/lib/python3.6/site-packages/stimela/cargo/cab/rmsynth3d/src:/stimela_mount/code:ro -v /24TB/floi/POL_TEST/.stimela_workdir-16067485787053518/passwd:/etc/passwd:rw -v /24TB/floi/POL_TEST/.stimela_workdir-16067485787053518/group:/etc/group:rw -v /home/floi/.local/bin/stimela_runscript:/docker_run:ro -v /24TB/floi/POL_TEST/msdir:/stimela_mount/msdir:rw -v /24TB/floi/POL_TEST/output/continuum/rm_dir:/stimela_mount/input:ro -v /24TB/floi/POL_TEST/output:/stimela_mount/output:rw -v /24TB/floi/POL_TEST/output/tmp:/stimela_mount/output/tmp:rw  -e CONFIG=/stimela_mount/configfile -e HOME=/stimela_mount/output -e STIMELA_MOUNT=/stimela_mount -e MSDIR=/stimela_mount/msdir -e INPUT=/stimela_mount/input -e OUTPUT=/stimela_mount/output -e TMPDIR=/stimela_mount/output/tmp --rm -w /stimela_mount/output --name rmsynth3d-1399823203836001606748578706498 stimela/rm-tools:1.6.9-1 /docker_run
# 740289314ad861452411174b72246c515a8b73d517cbdd1dc83ed04c72c02329
2020-11-30 15:02:58 STIMELA.rmsynth3d INFO: Starting container [rmsynth3d-1399823203836001606748578706498]. Timeout set to -1. The container ID is printed below.
# running docker start -a rmsynth3d-1399823203836001606748578706498
# 2020-11-30 15:02:59: Initial memory state:
# 2020-11-30 15:02:59:               total        used        free      shared  buff/cache   available
# 2020-11-30 15:02:59: Mem:           251G        1.3G         74G        2.1M        175G        248G
# 2020-11-30 15:02:59: Swap:           63G         13M         63G
# 2020-11-30 15:02:59: Running rmsynth3d -i /stimela_mount/input/4k_RMSYNTH-NGC1365_3-I.fits -s 10 -v /stimela_mount/input/4k_RMSYNTH-NGC1365_3-Q.fits /stimela_mount/input/4k_RMSYNTH-NGC1365_3-U.fits /stimela_mount/input/freqs.dat
# Reading /stimela_mount/input/4k_RMSYNTH-NGC1365_3-I.fits ...
# done.
# Dimensions of the input cube are:  NAXIS1 = 2048  NAXIS2 = 2048  NAXIS3 = 19
# Dimensions of the input array are:  (19, 2048, 2048)
# Reading /stimela_mount/input/4k_RMSYNTH-NGC1365_3-Q.fits ...
# done.
# Dimensions of the input cube are:  NAXIS1 = 2048  NAXIS2 = 2048  NAXIS3 = 19
# Dimensions of the input array are:  (19, 2048, 2048)
# Reading /stimela_mount/input/4k_RMSYNTH-NGC1365_3-U.fits ...
# done.
# Dimensions of the input cube are:  NAXIS1 = 2048  NAXIS2 = 2048  NAXIS3 = 19
# Dimensions of the input array are:  (19, 2048, 2048)
# PhiArr = -5229.67 to 5229.67 by 52.30 (201 chans).
# Weight type is 'uniform'.
# Running RM-synthesis by channel.
#   [                                        ] 0%
#   [                                        ] 0%
#   [                                        ] 0%
#   [                                        ] 1%
#   [                                        ] 1%
#   [                                        ] 2%
#   [=                                       ] 2%
#   [=                                       ] 3%
#   [=                                       ] 3%
#   [=                                       ] 4%
#   [=                                       ] 4%
#   [==                                      ] 5%
#   [==                                      ] 5%
#   [==                                      ] 6%
#   [==                                      ] 6%
#   [==                                      ] 7%
#   [===                                     ] 7%
#   [===                                     ] 8%
^[[B#   [===                                     ] 8%
#   [===                                     ] 9%
#   [===                                     ] 9%
#   [====                                    ] 10%
#   [====                                    ] 10%
#   [====                                    ] 11%
#   [====                                    ] 11%
#   [====                                    ] 12%
#   [=====                                   ] 12%
#   [=====                                   ] 13%
#   [=====                                   ] 13%
#   [=====                                   ] 14%
#   [=====                                   ] 14%
#   [======                                  ] 15%
#   [======                                  ] 15%
#   [======                                  ] 16%
#   [======                                  ] 16%
#   [======                                  ] 17%
#   [=======                                 ] 17%
#   [=======                                 ] 18%
#   [=======                                 ] 18%
#   [=======                                 ] 19%
#   [=======                                 ] 19%
#   [========                                ] 20%
#   [========                                ] 20%
#   [========                                ] 21%
#   [========                                ] 21%
#   [========                                ] 22%
#   [=========                               ] 22%
#   [=========                               ] 23%
#   [=========                               ] 23%
#   [=========                               ] 24%
#   [=========                               ] 24%
#   [==========                              ] 25%
#   [==========                              ] 25%
#   [==========                              ] 26%
#   [==========                              ] 26%
#   [==========                              ] 27%
#   [===========                             ] 27%
#   [===========                             ] 28%
#   [===========                             ] 28%
#   [===========                             ] 29%
#   [===========                             ] 29%
#   [============                            ] 30%
#   [============                            ] 30%
#   [============                            ] 31%
#   [============                            ] 31%
#   [============                            ] 32%
#   [=============                           ] 32%
#   [=============                           ] 33%
#   [=============                           ] 33%
#   [=============                           ] 34%
#   [=============                           ] 34%
#   [==============                          ] 35%
#   [==============                          ] 35%
#   [==============                          ] 36%
#   [==============                          ] 36%
#   [==============                          ] 37%
#   [===============                         ] 37%
#   [===============                         ] 38%
#   [===============                         ] 38%
#   [===============                         ] 39%
#   [===============                         ] 39%
#   [================                        ] 40%
#   [================                        ] 40%
#   [================                        ] 41%
#   [================                        ] 41%
#   [================                        ] 42%
#   [=================                       ] 42%
#   [=================                       ] 43%
#   [=================                       ] 43%
#   [=================                       ] 44%
#   [=================                       ] 44%
#   [==================                      ] 45%
#   [==================                      ] 45%
#   [==================                      ] 46%
#   [==================                      ] 46%
#   [==================                      ] 47%
#   [===================                     ] 47%
#   [===================                     ] 48%
#   [===================                     ] 48%
#   [===================                     ] 49%
#   [===================                     ] 49%
#   [====================                    ] 50%
#   [====================                    ] 50%
#   [====================                    ] 51%
#   [====================                    ] 51%
#   [====================                    ] 52%
#   [=====================                   ] 52%
#   [=====================                   ] 53%
#   [=====================                   ] 53%
#   [=====================                   ] 54%
#   [=====================                   ] 54%
#   [======================                  ] 55%
#   [======================                  ] 55%
#   [======================                  ] 56%
#   [======================                  ] 56%
#   [======================                  ] 57%
#   [=======================                 ] 57%
#   [=======================                 ] 58%
#   [=======================                 ] 58%
#   [=======================                 ] 59%
#   [=======================                 ] 59%
#   [========================                ] 60%
#   [========================                ] 60%
#   [========================                ] 61%
#   [========================                ] 61%
#   [========================                ] 62%
#   [=========================               ] 62%
#   [=========================               ] 63%
#   [=========================               ] 63%
#   [=========================               ] 64%
#   [=========================               ] 64%
#   [==========================              ] 65%
#   [==========================              ] 65%
#   [==========================              ] 66%
#   [==========================              ] 66%
#   [==========================              ] 67%
#   [===========================             ] 67%
#   [===========================             ] 68%
#   [===========================             ] 68%
#   [===========================             ] 69%
#   [===========================             ] 69%
#   [============================            ] 70%
#   [============================            ] 70%
#   [============================            ] 71%
#   [============================            ] 71%
#   [============================            ] 72%
#   [=============================           ] 72%
#   [=============================           ] 73%
#   [=============================           ] 73%
#   [=============================           ] 74%
#   [=============================           ] 74%
#   [==============================          ] 75%
#   [==============================          ] 75%
#   [==============================          ] 76%
#   [==============================          ] 76%
#   [==============================          ] 77%
#   [===============================         ] 77%
#   [===============================         ] 78%
#   [===============================         ] 78%
#   [===============================         ] 79%
#   [===============================         ] 79%
#   [================================        ] 80%
#   [================================        ] 80%
#   [================================        ] 81%
#   [================================        ] 81%
#   [================================        ] 82%
#   [=================================       ] 82%
#   [=================================       ] 83%
#   [=================================       ] 83%
#   [=================================       ] 84%
#   [=================================       ] 84%
#   [==================================      ] 85%
#   [==================================      ] 85%
#   [==================================      ] 86%
#   [==================================      ] 86%
#   [==================================      ] 87%
#   [===================================     ] 87%
#   [===================================     ] 88%
#   [===================================     ] 88%
#   [===================================     ] 89%
#   [===================================     ] 89%
#   [====================================    ] 90%
#   [====================================    ] 90%
#   [====================================    ] 91%
#   [====================================    ] 91%
#   [====================================    ] 92%
#   [=====================================   ] 92%
#   [=====================================   ] 93%
#   [=====================================   ] 93%
#   [=====================================   ] 94%
#   [=====================================   ] 94%
#   [======================================  ] 95%
#   [======================================  ] 95%
#   [======================================  ] 96%
#   [======================================  ] 96%
#   [======================================  ] 97%
#   [======================================= ] 97%
#   [======================================= ] 98%
#   [======================================= ] 98%
#   [======================================= ] 99%
#   [======================================= ] 99%
#   [========================================] 100%
# Calculating 1D RMSF and replicating along X & Y axes.
# > RM-synthesis completed in 168.57 seconds.
# Saving the dirty FDF, RMSF and ancillary FITS files.
# > /stimela_mount/input/FDF_real_dirty.fits
# Traceback (most recent call last):
#   File "/usr/local/bin/rmsynth3d", line 8, in <module>
#     sys.exit(main())
#   File "/usr/local/lib/python3.6/dist-packages/RMtools_3D/do_RMsynth_3D.py", line 604, in main
#     verbose            = verbose)
#   File "/usr/local/lib/python3.6/dist-packages/RMtools_3D/do_RMsynth_3D.py", line 315, in writefits
#     hdu0.writeto(fitsFileOut, output_verify="fix", overwrite=True)
#   File "/usr/local/lib/python3.6/dist-packages/astropy/utils/decorators.py", line 535, in wrapper
#     return function(*args, **kwargs)
#   File "/usr/local/lib/python3.6/dist-packages/astropy/io/fits/hdu/base.py", line 372, in writeto
#     checksum=checksum)
#   File "/usr/local/lib/python3.6/dist-packages/astropy/utils/decorators.py", line 535, in wrapper
#     return function(*args, **kwargs)
#   File "/usr/local/lib/python3.6/dist-packages/astropy/io/fits/hdu/hdulist.py", line 932, in writeto
#     fileobj = _File(fileobj, mode=mode, overwrite=overwrite)
#   File "/usr/local/lib/python3.6/dist-packages/astropy/utils/decorators.py", line 535, in wrapper
#     return function(*args, **kwargs)
#   File "/usr/local/lib/python3.6/dist-packages/astropy/io/fits/file.py", line 175, in __init__
#     self._open_filename(fileobj, mode, overwrite)
#   File "/usr/local/lib/python3.6/dist-packages/astropy/io/fits/file.py", line 564, in _open_filename
#     self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
#   File "/usr/local/lib/python3.6/dist-packages/astropy/io/fits/util.py", line 397, in fileobj_open
#     return open(filename, mode, buffering=0)
# OSError: [Errno 30] Read-only file system: '/stimela_mount/input/FDF_real_dirty.fits'
# 2020-11-30 15:06:05: rmsynth3d exited with code 1
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR: docker returns error code 1
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR: job failed at 2020-11-30 15:06:06.017170 after 0:03:07.296490
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR: Traceback (most recent call last):
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/recipe.py", line 703, in run
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:     job.run_job()
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/recipe.py", line 423, in run_job
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:     self.job.start(output_wrangler=self.apply_output_wranglers)
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/docker.py", line 167, in start
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:     kill_callback=lambda: utils.xrun("docker", ["kill", self.name]))
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:   File "/home/floi/.local/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2020-11-30 15:06:06 STIMELA.rmsynth3d ERROR: stimela.utils.StimelaCabRuntimeError: docker returns error code 1
2020-11-30 15:06:06 STIMELA.run INFO: Completed jobs : []
2020-11-30 15:06:06 STIMELA.run INFO: Remaining jobs : []
2020-11-30 15:06:06 STIMELA.run INFO: Saving pipeline information in .last_run.json
Traceback (most recent call last):
  File "/home/floi/.local/bin/stimela", line 11, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/floi/.local/lib/python3.6/site-packages/stimela/main.py", line 567, in main
    _cmd(argv)
  File "/home/floi/.local/lib/python3.6/site-packages/stimela/main.py", line 195, in run
    exec(stdr.read(), _globals)
  File "<string>", line 35, in <module>
  File "/home/floi/.local/lib/python3.6/site-packages/stimela/recipe.py", line 754, in run
    raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'rmsynth obs' failed: docker returns error code 1
```

**Comment by SpheMakh** [comment]
It wants to put the outputs in the input folder which is read only. Is there a way to specify an output folder, or do you do it via the prefix (` rmsynth -o  outdir/<foo.bar>`)? But you can try (not that I added ":output" to the input file names)

```
run.add("cab/rmsynth3d",
            "rmsynth3d",
             {
                "fitsq": "4k_RMSYNTH-NGC1365_3-Q.fits:output",
                "fitsu": "4k_RMSYNTH-NGC1365_3-U.fits:output",
                "fitsi": "4k_RMSYNTH-NGC1365_3-I.fits:output",
                "freqs": "freqs.dat:output",
                "prefixout": "prova",
                "s": 10,
                "v": True,
             },
             input=INPUT, output="output/continuum/rm_dir",
             label="rmsynth obs")
```
