### ISSUE TITLE
Configuratt branch not reading wsclean cab parameter 

### ISSUE THREAD

**Issue by ulricharmel** [ratt-ru/Stimela#725]
(env-stimela-jake) ulrich@jake:~/AveragingTime$ stimela exec test_configuratt.yml
2021-05-28 04:53:48 STIMELA INFO: starting
2021-05-28 04:53:57 STIMELA INFO: no configuration files, so using defaults
2021-05-28 04:53:59 STIMELA INFO: backend is docker
2021-05-28 04:53:59 STIMELA INFO: loading recipe/config test_configuratt.yml
2021-05-28 04:53:59 STIMELA INFO: test_configuratt.yml contains the following recipe sections: 'jove'
2021-05-28 04:54:00 STIMELA INFO: selected recipe is 'jove'
Traceback (most recent call last):
  File "/home/ulrich/env-stimela-jake/bin/stimela", line 33, in <module>
    sys.exit(load_entry_point('stimela', 'console_scripts', 'stimela')())
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ulrich/env-stimela-jake/Stimela/stimela/commands/exxec.py", line 200, in exxec
    outputs = step.run()
  File "/home/ulrich/env-stimela-jake/Stimela/stimela/kitchen/recipe.py", line 134, in run
    self.prevalidate()
  File "/home/ulrich/env-stimela-jake/Stimela/stimela/kitchen/recipe.py", line 115, in prevalidate
    self.finalize()
  File "/home/ulrich/env-stimela-jake/Stimela/stimela/kitchen/recipe.py", line 109, in finalize
    self.cargo.finalize(config, log=self.log, hier_name=hier_name, nesting=nesting+1)
  File "/home/ulrich/env-stimela-jake/Stimela/stimela/kitchen/recipe.py", line 451, in finalize
    step.finalize(config, hier_name=f"{hier_name}.{label}", nesting=nesting)
  File "/home/ulrich/env-stimela-jake/Stimela/stimela/kitchen/recipe.py", line 107, in finalize
    self.cargo = Cab(**config.cabs[self.cab])
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 321, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/ulrich/env-stimela-jake/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: cabs.wsclean.command
	full_key: cabs.wsclean.command
	reference_type=Any
	object_type=Cab

This is the folder with my test run
directory: /home/ulrich/test-configuratt   on jake
command: stimela exec test_configuratt.yml
The virtual environment directory is /home/ulrich/env-stimela-jake
Both Stimela and scabha  codes are in the virtual environment directory

**Comment by o-smirnov** [comment]
Ah, cr@p, sorry @ulricharmel, I forgot to tell you to ``pip install --upgrade omegaconf --pre`` or ``pip install git+https://github.com/omry/omegaconf``. 

It's just a bug in OmegaConf 2.0 that's already been fixed in master and 2.1rc1.

**Comment by o-smirnov** [comment]
I've modified setup.py to install OmegaConf >= 2.1pre1, so this should not happen again.
